- name: variable
  hosts: localhost
  vars_prompt:  
    - name: USERNAME
      prompt: please enter username
      private: false
    - name: PASSWORD
      prompt: please enter password
      private: true
  tasks:
    - name: print variables
      vars:
        course: "devops "
      ansible.builtin.debug:
        msg: "my cpurse is {{course}}. my couch is {{trainer}}. time duration is {{duration}}"
