#function/filters
- name: filters
  hosts: localhost
  vars:
    ages: [25,35,45]
  tasks:
  - name: print min and max
    ansible.builtin.debug:
      msg: "min age {{ ages | min }}, max age {{ ages | max }}"