- name: conditons
  hosts: localhost
  vars:
    course: "devops"
    number: 5
  tasks:
  - name: print condition
  ansible.builtin.debug:
    msg: "my course is {{course}}"
    msg: "entered number {{number}}"
  when: number | int>0