- name: conditons
  hosts: localhost
  vars:
    course: "devops"
    number: 5
  tasks:
    - name: print condition   
      ansible.builtin.debug:
        msg: "my course is {{ course }}"
      when: number | int > 0
    - name: print number
      ansible.builtin.debug:
        msg: "entered number {{ number }}"
